
-- 1. ENUMS
DO $$ BEGIN
    CREATE TYPE public.order_status AS ENUM (
        'novo_pedido',
        'a_separar',
        'separado',
        'a_enviar',
        'enviado',
        'recuperar_carrinho',
        'concluido',
        'cancelado'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.transaction_type AS ENUM ('Entrada', 'Saída');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.transaction_status AS ENUM ('Completo', 'Pendente', 'Em Atraso');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. TABLES

-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Customers
CREATE TABLE IF NOT EXISTS public.customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    cpf TEXT,
    birth_date DATE,
    gender TEXT,
    notes TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Customer Addresses
CREATE TABLE IF NOT EXISTS public.customer_addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'Residencial',
    street TEXT,
    number TEXT,
    complement TEXT,
    neighborhood TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    is_primary BOOLEAN DEFAULT false,
    is_default BOOLEAN DEFAULT false,
    is_pickup_location BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Products
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    name TEXT,
    description TEXT,
    price NUMERIC,
    cost NUMERIC,
    sku TEXT,
    stock_quantity INTEGER DEFAULT 0,
    category TEXT,
    brand TEXT,
    supplier TEXT,
    image_url TEXT,
    variations JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Colors and Sizes (Auxiliary)
CREATE TABLE IF NOT EXISTS public.colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    name TEXT NOT NULL,
    hex_code TEXT
);

CREATE TABLE IF NOT EXISTS public.sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    value TEXT NOT NULL,
    category TEXT NOT NULL
);

-- Product Variants
CREATE TABLE IF NOT EXISTS public.product_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    name TEXT,
    sku TEXT,
    price NUMERIC,
    stock_quantity INTEGER DEFAULT 0,
    color_id BIGINT REFERENCES public.colors(id),
    size_id BIGINT REFERENCES public.sizes(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Orders
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_email TEXT,
    status public.order_status DEFAULT 'novo_pedido'::public.order_status NOT NULL,
    total_price NUMERIC DEFAULT 0,
    payment_method TEXT,
    delivery_type TEXT,
    origin TEXT,
    items JSONB,
    address JSONB,
    notes TEXT,
    product_id BIGINT REFERENCES public.products(id), -- Legacy support or single product ref
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Transactions (Financial)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    type public.transaction_type NOT NULL,
    origin TEXT NOT NULL,
    payment_method TEXT,
    value NUMERIC NOT NULL,
    status public.transaction_status DEFAULT 'Pendente'::public.transaction_status,
    notes TEXT,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- General policy for all tables: users can only see/manage their own data
CREATE POLICY "Users can manage their own profile" ON public.profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY "Users can manage their own customers" ON public.customers FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own customer addresses" ON public.customer_addresses FOR ALL 
    USING (EXISTS (SELECT 1 FROM public.customers WHERE id = customer_addresses.customer_id AND user_id = auth.uid()));
CREATE POLICY "Users can manage their own products" ON public.products FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own colors" ON public.colors FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own sizes" ON public.sizes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own product variants" ON public.product_variants FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own orders" ON public.orders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own transactions" ON public.transactions FOR ALL USING (auth.uid() = user_id);

-- 4. FUNCTIONS & TRIGGERS

-- Auto create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Auto update updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_customers BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Stock management functions
CREATE OR REPLACE FUNCTION public.decrement_stock(p_product_id BIGINT, p_quantity INTEGER, p_variant_id UUID DEFAULT NULL)
RETURNS VOID AS $$
BEGIN
    IF p_variant_id IS NOT NULL THEN
        UPDATE public.product_variants
        SET stock_quantity = stock_quantity - p_quantity
        WHERE id = p_variant_id;
    ELSE
        UPDATE public.products
        SET stock_quantity = stock_quantity - p_quantity
        WHERE id = p_product_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to automatically decrement stock when order is sent/completed
CREATE OR REPLACE FUNCTION public.trigger_decrement_stock_on_order_status()
RETURNS TRIGGER AS $$
DECLARE
    item RECORD;
BEGIN
    -- Check if status changed to 'enviado' or 'concluido'
    IF (NEW.status = 'enviado' OR NEW.status = 'concluido') AND (OLD.status != 'enviado' AND OLD.status != 'concluido') THEN
        IF NEW.items IS NOT NULL AND jsonb_array_length(NEW.items) > 0 THEN
            FOR item IN SELECT * FROM jsonb_to_recordset(NEW.items) AS x(product_id BIGINT, quantity INTEGER, variant_id UUID)
            LOOP
                PERFORM public.decrement_stock(item.product_id, item.quantity, item.variant_id);
            END LOOP;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER tr_decrement_stock_on_order_status
    AFTER UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.trigger_decrement_stock_on_order_status();

-- 5. STORAGE
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'products');
CREATE POLICY "Authenticated users can upload images" ON storage.objects FOR INSERT 
    WITH CHECK (bucket_id = 'products' AND auth.role() = 'authenticated');
CREATE POLICY "Users can update their own images" ON storage.objects FOR UPDATE 
    USING (bucket_id = 'products' AND auth.uid() = owner);
CREATE POLICY "Users can delete their own images" ON storage.objects FOR DELETE 
    USING (bucket_id = 'products' AND auth.uid() = owner);
