// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szpkqmejukrjeablpwjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cGtxbWVqdWtyamVhYmxwd2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjAxNTIsImV4cCI6MjA2NTU5NjE1Mn0.ut0nqTX85FA7R4wLssOOiiBpPgwPT91vI0UatYy719o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);